### ISSUE TITLE
Add C Header Gaurds

### ISSUE THREAD

**Issue by AlexKlimaj** [Broadcom/AFBR-S50-API#1]
Could you add C Header Guards to all the headers? It makes it easier to include in C++ projects.
For example.
https://github.com/PX4/PX4-Autopilot/blob/master/src/drivers/distance_sensor/broadcom/afbrs50/Inc/api/argus_api.h#L41-L43

**Comment by c-berger** [comment]
Thanks for your feedback. We will add such guards in the next version...

**Comment by c-berger** [comment]
The header guards have been added with commit 9110d00.
