### ISSUE TITLE
RISC-V libary compilation

### ISSUE THREAD

**Issue by Somososan** [Broadcom/AFBR-S50-API#11]
Hi,

Is there a possibility to see the libary being recompiled for risc-v targets like IMC or IMAC. This would open up the usage with the popular ESP32 platform and other low cost modules.

Thanks

**Comment by c-berger** [comment]
Hi Somososan,

thanks for your interest in our sensor, we certainly highly appreciate that. We're also aware of growing interest in the RISC-V architecture and thus it would be nice to add support for that to our API. Unfortunately, as the demand for RISC-V from our customers is still very minor, we do not plan to port the API to the RISC-V now or in near future. The ARM Cortex-M architecture is still the most requested architecture and we do not have the resources to carry out the required efforts in porting, testing and maintaining a second architecture like the RISC-V. 

I am sorry to not have a positive answer, though I still like to encourage you to reach out to our [TOF support team](mailto:support.TOF@broadcom.com) and lay out your application requirements. I am sure we can find a solution, for example using the [sensor board by MikroE](https://www.mikroe.com/bdc-afbr-s50-tof-sensor-board).

Kind regards.
