### ISSUE TITLE
Reading the sensor board with a microcontroller

### ISSUE THREAD

**Issue by walkthedog2** [Broadcom/AFBR-S50-API#17]
I'm able to display measurements using a serial to USB adapter, but I am unable to receive data in any UART configuration on the STM32 (DMA/Interrupt/Poll).
I've checked the signal using an oscilloscope and it all looks fine. I'm using the high speed 1000 Hz example code.

Has anyone been successful reading the sensor from a microcontroller?
Any assistance would be appreciated. Apologies if this is the wrong place to post this.

Sebastian Thwaites
University of Newcastle

**Comment by c-berger** [comment]
Hi Sebastian,
thanks for you question but that's a bit difficult to answer without more information.
As you say you can receive data via an serial-to-USB adapter, it's probably an issue with your STM32 board setup. 
I guess there is either some issue in pin muxing or UART configuration. Have you initialized the pins to UART mode? Is the UART peripheral correctly enabled (clock gating?) and initialized (115200 bps, 8N1, no handshake, no flow control)?
If this doesn't give you a hint on where to find the issue, please double check the UART of your STM board with the serial-to-USB adapter first. Also you may want to follow some tutorials on how to setup UART, for example: https://wiki.st.com/stm32mcu/wiki/STM32StepByStep:Step3_Introduction_to_the_UART
