### ISSUE TITLE
Unable to Build Example App with Xtalk Calibration Enabled

### ISSUE THREAD

**Issue by hurstk2** [Broadcom/AFBR-S50-API#23]
Hi,
I am trying to calibrate the AFBR-S50 Reference Board by MikroElektronika, but am having problems while attempting to build the Example App.

I cloned the main branch of the repository [AFBR-S50-API](https://github.com/Broadcom/AFBR-S50-API/tree/main) in January this year and am using e2studio (Version: 2023-10 (23.10.0)) with FSP 4.4.0 for development.

The problem is as follows:
- When I set the RUN_XTALK_CALIBRATION flag to 1 in order to enable crosstalk calibration, the build fails with the following error: 
`fatal error: argus_xtalk_cal_cli.h: No such file or directory`
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/62c8afdc-292a-48c1-977b-c20d5dba2104)
- It's worth noting that the build works successfully when RUN_XTALK_CALIBRATION is set to 0.
- The Xtalk-CLI directory is not listed in includes.
![Screenshot 2024-04-18 095331](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/39704981-3614-4dcd-bfce-ff337133c251)
- Adding the directory to includes via _Properties -> C/C++ Build -> Settings -> GNU ARM Cross C Compiler -> Includes_ results in the same error.
- Similarly, adding the directory via _Properties -> C/C++ Build -> Settings -> GNU ARM Cross C Linker -> Libraries_ also results in build errors.

I would appreciate your advice on how to resolve this issue so that I can calibrate the sensor. Thank you in advance!

**Comment by c-berger** [comment]
Hi and thanks for reporting that issue. The project was missing the source folder and include references for the XTALK CLI. I just have pushed a fix to the main branch. 

Please make sure you refresh (right click on the project -> Refresh or simply restart e2Studio) and do a clean build to make sure the changes are properly applied after pulling from the remote.
