### ISSUE TITLE
Unable to Build Example App

### ISSUE THREAD

**Issue by hurstk2** [Broadcom/AFBR-S50-API#24]
Hi, this is a follow up to issue https://github.com/Broadcom/AFBR-S50-API/issues/23 posted last Thursday. FSP and e2studio version are still the same.

I have downloaded the updated repository and the project now fails to build even when RUN_XTALK_CALIBRATION is set to 0.

The errors from three attempts to run when RUN_XTALK_CALIBRATION is set to 0 can be found below:
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/e8352621-5020-4f03-8207-ccd825ed3e40)
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/eb6acae5-4ef9-4f8e-985e-40f85f61cf70)
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/6506f90d-f66a-4802-8652-ebfb5cf94558)

The errors from three attempts to run when RUN_XTALK_CALIBRATION is set to 1 can be found below:
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/2c760609-6cc2-4f11-bc71-b49f253fd2c3)
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/f697bf22-2c27-4013-852b-9ef71bc246ab)
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/f1a96b3a-9a46-4c9e-b560-d337484a9521)

The project was cleaned and refreshed between each attempt.
Building the Can App also fails with similar errors when it succeeded before the update.

**Comment by hurstk2** [comment]
I have recloned the version from this commit https://github.com/Broadcom/AFBR-S50-API/commit/421a55e2f9022c3b6d209047d5a18926a16773c8 which is the version I previously had and both the CAN App and the Example App work as they did before

CAN APP Build Output:
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/3553769c-73d7-4590-b0f2-1c57286566c4)
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/b1823540-13e0-46a2-975b-a1434bd7010c)

Example App Build Output:
RUN_XTALK_CALIBRATION 0
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/01ba5e65-3b14-44f5-85ba-878f0db56d25)
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/16d24d57-0956-44bb-bc3f-babdc2dca2fd)
RUN_XTALK_CALIBRATION 1
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/13ddefa3-f222-4230-8246-a82361f5fb82)
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/0cf40c1e-b6fe-4055-bc55-8dc7ccf39e8c)

______________________________________________________________________________________________________________________________________
I decided to run some tests to see which version the CAN APP and Example App stopped building for me.

The first commit when the Example app fails to build is https://github.com/Broadcom/AFBR-S50-API/commit/390912d103caa6966e45f70f700b04d91f1453e1

https://github.com/Broadcom/AFBR-S50-API/commit/390912d103caa6966e45f70f700b04d91f1453e1 Example App build output:
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/aa90fd37-12a7-4f8d-b9e7-9c9c40180377)

I found that if I went to https://github.com/Broadcom/AFBR-S50-API/commit/2122864d245efed96f3840d89fd68b5aa49545dc browse files and cloned the repository from there the CAN App successfully builds so I decided to try recloning the main branch and the CAN App successfully built with no errors but the version I got yesterday still fails to build.

The three attempts to build the Example App from the new clone of the main branch still failed with the following errors:
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/159a8d1d-f96e-418c-b530-41bee9d6d411)
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/f22cdbbb-9414-45ec-b532-d1bece3bae1a)
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/5f237324-1014-4f04-a0b1-93576a4f7be8)

**Comment by c-berger** [comment]
Hi there, thanks for tracking down the commit that introduces the issue. Seems like the `Q11_4_ONE` is not defined in those projects. That should be easy to solve. I will take care of that immediately and let you know once it's fixed.

**Comment by c-berger** [comment]
Hi, seems like a type has caused the issue. Oddly that I didn't recognize that in the first place.
May you please try the latest main commit? It should fix this problem...

**Comment by hurstk2** [comment]
Thank you so much for your help, both the CAN App and the Example App now build successfully.

CAN APP Build Output:
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/2ee575f3-f910-4193-b227-149293065449)

Example App Build Output:
RUN_XTALK_CALIBRATION 0
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/9707af0a-7b89-42d9-8095-d273757f0131)
RUN_XTALK_CALIBRATION 1
![image](https://github.com/Broadcom/AFBR-S50-API/assets/77619572/3e26cc50-0030-4c8a-bf53-9b8a14232b00)
