### ISSUE TITLE
Range Offset Calibration function

### ISSUE THREAD

**Issue by FloVesuv** [Broadcom/AFBR-S50-API#27]
Hi,

As I asked in my previous issue, I want to know how can I integrate the Range Offset Calibration function into my code?

![image](https://github.com/Broadcom/AFBR-S50-API/assets/152492585/1efd79b1-a5f8-4527-928e-d2aa3a0feb8f)

Thank you for your support

**Comment by c-berger** [comment]
Please have a look in the API Reference Manual:
- [Argus_ExecuteRelativeRangeOffsetCalibrationSequence](https://broadcom.github.io/AFBR-S50-API/group__argus__meas.html#gabfbc2d139e090be5e06930814c4bf48e)
- [Argus_ExecuteAbsoluteRangeOffsetCalibrationSequence](https://broadcom.github.io/AFBR-S50-API/group__argus__meas.html#ga9ce494f75f6c54e1eebec6e1f0ec89d0)
