### ISSUE TITLE
Creation of Japanese README

### ISSUE THREAD

**Issue by waarrk** [Broadcom/AFBR-S50-API#3]
I would like to use this sensor. Create Japanese version of README

**Comment by goetzfrv** [comment]
Thanks Waarrk for your request. Could you briefly explain what you did and why you translated the readme again into japanese?
Is there something which we can improve in the english version? Please do let us know.
Thanks

**Comment by waarrk** [comment]
Because this sensor is special, interest in it is spreading among students in Japan as well. If there is a Japanese README, I translated it because I thought it would be useful for developers who will be using this sensor in the future.

I just noticed that the English version of my commit has an automatic indentation fix... it doesn't seem to be a problem.

Regarding the English version of the README, it would be nice if the usage for Coretex on the official HP was expanded.
Best regards,

**Comment by c-berger** [comment]
Closed as we can not maintain Japanese readme, see: https://github.com/Broadcom/AFBR-S50-API/pull/4#issuecomment-1235219212
