### ISSUE TITLE
Incorrect work of excel for Crosstalk Calibration with Explorer

### ISSUE THREAD

**Issue by shpegun60** [Broadcom/AFBR-S50-API#30]
The rows "dS(ext)_corr" and  "dC(ext)_corr" don't have a formula at all, which means I can't create a correct output file,. Please help!!! "AFBR-S50-XTK.zip --> CoverglassXtalkcalibration_v1.4.x_template.xlsx"  in https://github.com/Broadcom/AFBR-S50-API/releases/tag/v1.4.4

![image](https://github.com/Broadcom/AFBR-S50-API/assets/70111075/6b33ef8e-f1ad-4a9f-9209-28c783c7a5bf)

**Comment by goetzfrv** [comment]
Hi shpegun60, sorry for the confusion in the Excel. Actually, most people directly use the API (C-code) version of the xtalk calibration as it does these calculations automatically and you just need to copy paste the xtalk table from your terminal.

In principle you can just copy&paste the values from dS(ext) and dC(ext) into the ..._corr columns and then work with the values in the blue list. Just in case you see spikes in your total xtalk values like shown figure 25 in the AFBR-S50-XTK application note 
![image](https://github.com/Broadcom/AFBR-S50-API/assets/82138424/587db143-c3b6-494f-b065-b037823f1137)

you may need to do an interpolation. 

Please see function `Interpolate_ActivePixels(argus_hnd_t * hnd)` in https://github.com/Broadcom/AFBR-S50-API/blob/main/AFBR-S50/Xtalk-CLI/argus_xtalk_cal_cli.c to see how to do the interpolation (actually averaging).

Best Regards!

**Comment by goetzfrv** [comment]
Hello Spehgun60,
please find the corrected Excel under https://github.com/Broadcom/AFBR-S50-API/releases/download/v1.5.6/AFBR-S50-XTK.zip.
Please consider that you might need to manually correct the values in case you need to interpolate because of peaks in the xtalk chart (see my last post). I will close this comment as this will resolve your issues.

**Comment by goetzfrv** [comment]
closed

**Comment by shpegun60** [comment]
Hello [goetzfrv](https://github.com/goetzfrv) 
Thanks for the fixed bug, sorry for not replying, solved the problem with the help of the console program as you recommended to me, thank you very much again!!
