### ISSUE TITLE
Get sensor temperature value on AFBR-S50MV85I

### ISSUE THREAD

**Issue by FloVesuv** [Broadcom/AFBR-S50-API#36]
Hi,

I want to get the sensor temperature on a modified AFBR_S50_Example_KL46z file.

Does this function already exist ?
I found some function in AFBR_S50_ExplorerApp_KL46z (sci folder), but what's the easiest way to import it in my project ?

Thank you.

**Comment by goetzfrv** [comment]
Hello FloVesuv,
you can find the chip temperature in the argus_results_aux_t struct. Please see https://broadcom.github.io/AFBR-S50-API/structargus__results__aux__t.html
Regards
