### ISSUE TITLE
Save absolute range offset calibration values

### ISSUE THREAD

**Issue by FloVesuv** [Broadcom/AFBR-S50-API#39]
Hi,

Hello, for my application, I am using the function of Argus_ExecuteAbsoluteRangeOffsetCalibrationSequence()

It works very well, but if there’s a power outage and I don’t recalibrate, the values are lost, which results in inaccurate measurements.

How can I save these values to memory so I can reuse them after a restart without having to recalibrate?

Thank you,

**Comment by c-berger** [comment]
Hi, this is possible either by implementing the non-volatile memory (NVM) module and let the API take care of saving stuff or by using the corresponding API functions and store the date manually.

For the NVM solution, have a look here:
https://broadcom.github.io/AFBR-S50-API/group__argus__nvm.html
It basically requires to implement the [NVM_WriteBlock](https://broadcom.github.io/AFBR-S50-API/group__argus__nvm.html#ga6a377265320f4a026896bf3718da3e99) and [NVM_ReadBlock](https://broadcom.github.io/AFBR-S50-API/group__argus__nvm.html#ga8a2466c2cf2e2651b45298703f936888) functions.

For the manual solution, you can use the 
- [Argus_GetCalibrationPixelRangeOffsets](https://broadcom.github.io/AFBR-S50-API/group__argus__cal.html#ga0a065a573c8800a93b8add2bf19ac926) 
- [Argus_SetCalibrationPixelRangeOffsets](https://broadcom.github.io/AFBR-S50-API/group__argus__cal.html#ga73e202090136dd1dde9ed98317f211da)
- [Argus_GetCalibrationGlobalRangeOffsets](https://broadcom.github.io/AFBR-S50-API/group__argus__cal.html#ga5f98415330a855d46a509654721f0a47)
- [Argus_SetCalibrationGlobalRangeOffsets](https://broadcom.github.io/AFBR-S50-API/group__argus__cal.html#ga581ffa1c5ceec9f8da6cb5b3d1c98b98)

Please also refer to the API documentation which should give additional information:
[Argus_ExecuteAbsoluteRangeOffsetCalibrationSequence](https://broadcom.github.io/AFBR-S50-API/group__argus__meas.html#ga9ce494f75f6c54e1eebec6e1f0ec89d0)
