### ISSUE TITLE
I want to see the file before compilation

### ISSUE THREAD

**Issue by waarrk** [Broadcom/AFBR-S50-API#9]
Hi! I want to browse the c language files in the implementation. If you don't mind the license, could you please upload the original files to create the compiled .a files under AFBR-S50-API/AFBR-S50/Lib/?

I would like to check the detailed implementation of the measurement algorithm and change the contents of the printed error message.

**Comment by goetzfrv** [comment]
Dear Waarrk,
thanks for your inquiry. Actually, our API is only available with the core functionalities of the pre-compiled library. The main reason for that is safety-related. The pre-compiled library preserves the ability to use our sensors within laser class l under each possible condition. Another intention of the library is a reduction of complexity for the user. If you want to get further information on your application please get in contact with support.tof@broadcom.com. Thank you
